LU decomposition

In [1]:
import numpy as np
import scipy
A = np.array([[4,3,2],[8,8,7],[6,6,9]])
P, L, U = scipy.linalg.lu(A)
print(P, L, U)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]] [[ 1.    0.    0.  ]
 [ 0.5   1.    0.  ]
 [ 0.75 -0.    1.  ]] [[ 8.    8.    7.  ]
 [ 0.   -1.   -1.5 ]
 [ 0.    0.    3.75]]


QR decomposition

In [2]:
import numpy as np
A=np.array([[4,3],[2,1]])
Q,R =np.linalg.qr(A)
print(Q,R)

[[-0.89442719 -0.4472136 ]
 [-0.4472136   0.89442719]] [[-4.47213595 -3.13049517]
 [ 0.         -0.4472136 ]]


singular value decomposition

In [3]:
import numpy as np
A =np.array([[1,2],[3,4],[4,5]])
U, S, VT = np.linalg.svd(A)
print(U, S, VT)

[[-0.26118278  0.92755323  0.26726124]
 [-0.59420931  0.0637036  -0.80178373]
 [-0.76072258 -0.36822122  0.53452248]] [8.41440825 0.44467267] [[-0.60452273 -0.79658789]
 [-0.79658789  0.60452273]]


Eigenvalue decomposition

In [4]:
import numpy as np
A=np.array([[1,3],[2,3]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues, eigenvectors)


[-0.64575131  4.64575131] [[-0.8767397  -0.6354064 ]
 [ 0.48096517 -0.7721779 ]]


Cholesky decomposition

In [5]:
import numpy as np
A=np.array([[16,4],[4,10]])
L= np.linalg.cholesky(A)
print(L)

[[4. 0.]
 [1. 3.]]


GROUP SIX
NAMALWA MILLIA 2023/DCSE/0070/SS
ADOKORACH NANCY 2023/DCSE/0004/SS
BAANDA GLORIA 2023/DCSE/0021/SS